on: [push]

jobs:
  hello_multistep_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello JS action step
        id: hello
        uses: JacobKorn/gh-actions-js-test@v1.2
        with:
          who-to-greet: 'everyone'
      - name: Get the JS output time
        run: echo "The JS time was ${{ steps.hello.outputs.time }}"
      - name: Get the JS output message
        run: echo "The JS output message is ${{ steps.hello.outputs.message }}"
      - name: Hello Docker action step
        id: helloDocker
        uses: JacobKorn/gh-actions-ruby-test@v1.2
        with:
          who-to-greet: 'Joe'
          message: "${{ steps.hello.outputs.message }}"
      - name: Get the Docker output time
        run: echo "The docker hello time was ${{ steps.helloDocker.outputs.time }}"
